# Generated by Django 6.0.2 on 2026-02-18 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_managers_alter_user_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.URLField(default='https://static.productionready.io/images/smiley-cyrus.jpg'),
        ),
    ]
