# Generated by Django 6.0.2 on 2026-02-19 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_rename_auhor_comment_author'),
        ('users', '0006_profile_follows'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='favorited', to='articles.article'),
        ),
    ]
