# Generated by Django 6.0.2 on 2026-02-17 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_article_slug_article_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(editable=False, max_length=100),
        ),
    ]
